### ISSUE TITLE
Rectangle must have four coordinates and not two

### ISSUE THREAD

**Issue by abhinav-shrivastava** [joaoventura/full-speed-python#19]
In the `Exercises with classes` chapter first exercise is to `Implement a class named “Rectangle” to store the coordinates of a rectangle given by (x1, y1) and (x2, y2)`.

What is not clear is how do you make a rectangle with only 2 coordinates? The only thing you can make out of two coordinates is a line segment.

Note that if you explicitly mention the assumption `assume the rectangle's sides are parallel to both X and Y axis.` then you can actually make a rectangle (which also makes it easier to calculate width and height). See the below example:

Eg. Take two coordinates (2,1) and (4,5) then the coordinates of the rectangle are (2,1), (2,5), (4,1) and (4,5). The width is then (x2 - x1) i.e. 4-2 = 2 and height is simply (y2 - y1) i.e. 5 -1 = 4.

I think the above assumption was made while designing the exercise but is not obvious. I feel adding the assumption would be useful for some of the readers out there, what do you think?

**Comment by abhinav-shrivastava** [comment]
@joaoventura will make a PR if this issue makes sense

**Comment by joaoventura** [comment]
Sorry for the late reply! You are correct: the two coordinates are the top left and bottom right corners. I'll make this a little bit more explicit.. 👍

**Comment by joaoventura** [comment]
Fixed in bc4d68e
