### ISSUE TITLE
Feature request: Support for numPy & pandas

### ISSUE THREAD

**Issue by Ahlid** [joaoventura/full-speed-python#23]
Hello!

NumPy & pandas are widely used libraries for arrays / matrix manipulation and data analysis with much use in the areas of Machine Learning and Data Science.

Do you think it makes sense to support this libraries in this full-speed-python book?

Thanks!

**Comment by pix9** [comment]
depends on what the aim behind writing the book?
if it is about putting up basic stuff limited to understanding syntax, then not necessary,
other aspect, how much about numpy and pandas is sufficient in this book if you choose to put in content?

**Comment by joaoventura** [comment]
Just saw this now.. I don't think it makes much sense to add those specific libraries. This is mostly a beginners introduction to Python, and those libraries assume specific needs.
