### ISSUE TITLE
Use Tuft's Textbook Style

### ISSUE THREAD

**Issue by JoshuaAdrianJones** [joaoventura/full-speed-python#6]
LaTeX best practices for modern books can be more easily done with a solid base, consider using a good book template such as Tufte's 

https://www.overleaf.com/latex/templates/book-design-inspired-by-edward-tufte/gcfbtdjfqdjh#.WrDfBGrFJhF

**Comment by JoshuaAdrianJones** [comment]
# Tuft-book example

---
@joaoventura  

 Hi Joao, I applied the tufte-book class to full speed python just to see how it would look, let me know what you think, if you like it I can submit at PR. Please see below:

 
---
[full-speed-python-tufte.pdf](https://github.com/joaoventura/full-speed-python/files/1845860/full-speed-python-tufte.pdf)

**Comment by joaoventura** [comment]
Hi @JoshuaAdrianJones, all the text is on the left side of the pages leaving a lot of unused space on the right side.. I've already bumped into this style and dismissed it because of that particular case.

**Comment by JoshuaAdrianJones** [comment]
Absolutely agree as is, the concept of Tuft-book is that we can keep the meat of the text separate from the elaboration and exposition.

We might like to have a running commentary or some other note that is too long for a footnote but not direct enough to keep in the main body of the text, so we can use the right hand side for that exposition.

If you've already considered this and dismissed it then that's okay - my issue was just the call for consideration!

I will close it as solved

Thanks
Josh
